apiVersion: v1
description: Provisioner and Storage Class for NFS Client based storage in the tagbio platform.
home: https://bitbucket.org/cloudfolks/nfs-provisioner
keywords:
  - nfs
  - storage
name: nfs-provisioner
sources:
  - https://bitbucket.org/cloudfolks/nfs-provisioner
  - https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner
version: 1.0.3
