environment:
  nfs:
    host: ''
    path: /
platform:
  namespaces:
    app: tagbio-app
    system: tagbio-system
  services: {}
jupyterhub:
  auth:
    admin:
      access: true
      users:
        - support@tag.bio
    custom:
      className: oauthenticator.generic.GenericOAuthenticator
      config:
        login_service: login-service
        client_id: tagbio-login-client
        client_secret: fe35df66-738c-4283-9ec2-1056175fd8a4
        token_url: https://app-aws-al2-200917.dev.tag.bio/login-service/auth/token
        userdata_url: https://app-aws-al2-200917.dev.tag.bio/login-service/auth/userInfo
        userdata_method: GET
        userdata_params: {'state': 'state'}
        username_key: email
    type: custom
    whitelist:
      users:
        - support@tag.bio
  hub:
    cookieSecret: "1c1269e8a73f90cc5420d73b86abb9aacf5f0d6ccc3c7c31b3bf9a0fba621a38"
    db:
      pvc:
        selector:
          matchLabels:
            jupyter.tag.bio/name: tagbio-jupyter-hub-storage-pv
      type: "sqlite-pvc"
    extraEnv:
      OAUTH2_AUTHORIZE_URL: https://app-aws-al2-200917.dev.tag.bio/login-service/auth/authorize
      OAUTH2_TOKEN_URL: https://app-aws-al2-200917.dev.tag.bio/login-service/auth/token
      OAUTH_CALLBACK_URL: https://jupyter-aws-al2-200917.dev.tag.bio/hub/oauth_callback
    initContainers:
      - command: ['sh', '-c', 'chown -R 1000:1000 /srv/jupyterhub']
        image: jupyterhub/k8s-hub:0.10.6
        imagePullPolicy: IfNotPresent
        name: chown
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 0
          runAsUser: 0
        volumeMounts:
        - mountPath: /srv/jupyterhub
          name: hub-db-dir
    networkPolicy:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - "jupyter-aws-al2-200917.dev.tag.bio"
    tls:
      - hosts:
          - jupyter-aws-al2-200917.dev.tag.bio
        secretName: tagbio-cluster
  proxy:
    chp:
      networkPolicy:
        enabled: false
    secretToken: "1c1269e8a73f90cc5420d73b86abb9aacf5f0d6ccc3c7c31b3bf9a0fba621a38"
    service:
      type: ClusterIP
  singleuser:
    defaultUrl: "/lab"
    image:
      name: jupyter/datascience-notebook
      tag: 'lab-2.2.9'
    initContainers:
      - command: ['sh', '-c', 'chown -R 1000:1000 /home/jovyan']
        image: jupyter/datascience-notebook
        imagePullPolicy: IfNotPresent
        name: chown
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 0
          runAsUser: 0
        volumeMounts:
          - mountPath: /home/jovyan
            name: home
            subPath: 'users/{username}'
    networkPolicy:
      enabled: false
    storage:
      type: static
      static:
        pvcName: tagbio-jupyter-users-storage-pvc
        subPath: 'users/{username}'

