apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    jupyter.tag.bio/name: tagbio-jupyter-hub-storage-pv
  name: tagbio-jupyter-hub-storage-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1000Gi
  nfs:
    path: /jupyter/hub
    readOnly: false
    server: {{ .Values.environment.nfs.host }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tagbio-jupyter-users-storage-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1000Gi
  nfs:
    path: /jupyter/users
    readOnly: false
    server: {{ .Values.environment.nfs.host }}
