---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    jupyter.tag.bio/name: tagbio-jupyter-hub-storage-pv
  name: tagbio-jupyter-hub-storage-pv
spec:
{{ if eq .Values.environment.storageVolumeType "azureFile" }}
  azureFile:
    readOnly: false
    secretName: {{ .Values.environment.azure.secret.name }}
    secretNamespace: {{ .Values.environment.azure.secret.namespace }}
    shareName: {{ .Values.environment.azure.fileshare.name }}/jupyter/hub
  mountOptions:
    - username={{ .Values.azure.storageAccountName }}
    - password={{ .Values.azure.storageAccountKey }}
    - 'serverino'
    - 'nosharesock'
    - 'actimeo=30'
    - 'dir_mode=0700'
    - 'file_mode=0600'
    - 'gid=100'
    - 'nolock'
    - 'uid=1000'
{{ end }}
{{ if eq .Values.environment.storageVolumeType "nfs" }}
  nfs:
    path: /jupyter/hub
    readOnly: false
    server: {{ .Values.environment.nfs.host }}
{{ end }}
{{ if eq .Values.environment.storageVolumeType "efs" }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.environment.efs.fileSystemId }}:/jupyter/hub
{{ end }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1000Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tagbio-jupyter-users-storage-pv
spec:
{{ if eq .Values.environment.storageVolumeType "azureFile" }}
  azureFile:
    readOnly: false
    secretName: {{ .Values.environment.azure.secret.name }}
    secretNamespace: {{ .Values.environment.azure.secret.namespace }}
    shareName: {{ .Values.environment.azure.fileshare.name }}/jupyter/users
  mountOptions:
    - username={{ .Values.azure.storageAccountName }}
    - password={{ .Values.azure.storageAccountKey }}
    - 'serverino'
    - 'nosharesock'
    - 'actimeo=30'
    - 'dir_mode=0700'
    - 'file_mode=0600'
    - 'gid=100'
    - 'nolock'
    - 'uid=1000'
{{ end }}
{{ if eq .Values.environment.storageVolumeType "nfs" }}
  nfs:
    path: /jupyter/users
    readOnly: false
    server: {{ .Values.environment.nfs.host }}
{{ end }}
{{ if eq .Values.environment.storageVolumeType "efs" }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.environment.efs.fileSystemId }}:/jupyter/users
{{ end }}
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1000Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tagbio-jupyter-users-shared-storage-pv
spec:
{{ if eq .Values.environment.storageVolumeType "azureFile" }}
  azureFile:
    readOnly: false
    secretName: {{ .Values.environment.azure.secret.name }}
    secretNamespace: {{ .Values.environment.azure.secret.namespace }}
    shareName: {{ .Values.environment.azure.fileshare.name }}/jupyter/users/tagbio-jupyter-shared
  mountOptions:
    - username={{ .Values.azure.storageAccountName }}
    - password={{ .Values.azure.storageAccountKey }}
    - 'serverino'
    - 'nosharesock'
    - 'actimeo=30'
    - 'dir_mode=0700'
    - 'file_mode=0600'
    - 'gid=100'
    - 'nolock'
    - 'uid=1000'
{{ end }}
{{ if eq .Values.environment.storageVolumeType "nfs" }}
  nfs:
    path: /jupyter/users/tagbio-jupyter-shared
    readOnly: false
    server: {{ .Values.environment.nfs.host }}
{{ end }}
{{ if eq .Values.environment.storageVolumeType "efs" }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.environment.efs.fileSystemId }}:/jupyter/users/tagbio-jupyter-shared
{{ end }}
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1000Gi
