apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tagbio-jupyter-storage-pvc
  labels:
    jupyter.tag.bio/name: tagbio-jupyter-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  volumeName: tagbio-jupyter-storage-pv
