{{- if .Values.aws }}
---
{{ include "tagbio.secretPreamble" (dict "name" "tagbio-aws" "namespace" .Values.tagbio.namespaces.app )}}
{{- if .Values.aws.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId }}
{{- end }}
{{- if .Values.aws.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey }}
{{- end }}
{{- if .Values.aws.region }}
  AWS_DEFAULT_REGION: {{ .Values.aws.region }}
{{- else }}
  AWS_DEFAULT_REGION: us-west-2
{{- end }}
{{- if .Values.aws.sessionToken }}
  AWS_SESSION_TOKEN: {{ .Values.aws.sessionToken }}
{{- end }}

---
{{ include "tagbio.secretPreamble" (dict "name" "tagbio-aws" "namespace" .Release.Namespace )}}
{{- if .Values.aws.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId }}
{{- end }}
{{- if .Values.aws.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey }}
{{- end }}
{{- if .Values.aws.region }}
  AWS_DEFAULT_REGION: {{ .Values.aws.region }}
{{- else }}
  AWS_DEFAULT_REGION: us-west-2
{{- end }}
{{- if .Values.aws.sessionToken }}
  AWS_SESSION_TOKEN: {{ .Values.aws.sessionToken }}
{{- end }}

{{- end }}
