apiVersion: v2
dependencies:
  - name: jupyterhub
    namespace: jupyterhub
    repository: https://jupyterhub.github.io/helm-chart
    version: 0.10.6
description: Jupyter Hub for the tagbio platform.
home: https://bitbucket.org/cloudfolks/tagbio-jupyter-chart
icon: https://live-tagbio.pantheonsite.io/wp-content/uploads/2019/09/tagbio.png
keywords:
  - jupyter
  - platform
  - tagbio
name: tagbio-jupyter
sources:
  - https://bitbucket.org/cloudfolks/tagbio-jupyter-chart
version: 1.0.89
